# Generated by Django 6.0.1 on 2026-01-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['index']},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('book', 'chapter', 'slug')},
        ),
    ]
